apiVersion: apps/v1
kind: Deployment
metadata:
  name: numgen8
  labels: 
    app: numgen8
spec:
  selector:
    matchLabels:
      app: numgen8
  template:
    metadata:
      labels:
        app: numgen8
    spec:
      containers:
      - name: numgen8
        image: jackflanagan93/num_gen_8:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001

