apiVersion: apps/v1
kind: Deployment
metadata:
  name: prizegenlarge
  labels: 
    app: prizegenlarge
spec:
  selector:
    matchLabels:
      app: prizegenlarge
  template:
    metadata:
      labels:
        app: prizegenlarge
    spec:
      containers:
      - name: client
        image: jackflanagan93/prize_generator_large:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
