apiVersion: apps/v1
kind: Deployment
metadata:
  name: textgenupper2
  labels: 
    app: textgenupper2
spec:
  selector:
    matchLabels:
      app: textgenupper2
  template:
    metadata:
      labels:
        app: textgenupper2
    spec:
      containers:
      - name: textgenupper2
        image: jackflanagan93/text_gen_upc2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
